name: Run Tests
run-name: Running Tests
on: [workflow_dispatch, workflow_call]
permissions:
  packages: read
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0

      - name: Run Tests
        run: |
          npm ci
          npm run all
          cd tests/out
          node all.js
